### ISSUE TITLE
Dockerize Node, React Apps with ease

### ISSUE THREAD

**Issue by thanatchakromsang** [thanatchakromsang/knowledge#6]
## Dockerize react, nodejs with node_modules
- [X] Local workflow
- [ ] Production workflow

### Local Example

**Dockerfile for local development**
- It will rebuild only when package.json or yarn.lock change
- Need to be use with docker-compose to mount `node_modules`
```Dockerfile
FROM node:8.11.3

RUN mkdir /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json .
COPY yarn.lock .

RUN yarn install --ignore-platform

# start app
CMD ["npm", "start"]
```

**docker-compose.yml**
- Work with [create-react-app](https://github.com/facebook/create-react-app) with almost to none configuration
- To use with other nodejs like `express`, `apollo-server` need to change exposed port
```yaml
version: "3.3"
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - HOME=/app
      - NODE_ENV=development
```

### Note
- [sources](https://mherman.org/blog/dockerizing-a-react-app/)
