### ISSUE TITLE
[Kubernetes] Mount secret as a files in pod

### ISSUE THREAD

**Issue by thanatchakromsang** [thanatchakromsang/knowledge#8]
## Mount secret as a file in Kubernetes pod
- Sometime some library only support credential through read `json` file like [nodejs-google-storage](https://github.com/googleapis/nodejs-storage) so we need a way to store `json` file

### Example (Deployment)
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.5.4
        imagePullPolicy: Always
        ports:
          - name: nginx
            containerPort: 80
        volumeMounts:
        - name: google-secret-key
          mountPath: /mnt/secret/key.json # where we want to put key.json
      volumes:
      - name: google-secret-key
        secret:
          secretName: google-secret # name of secret files
          items: # we want to pick specific key from google-secret
          - key: secret # key of encoded secret in google-secret
            path: key.json # where we want to put key in (it can be path)
```

### Note
- [sources](https://kubernetes.io/docs/concepts/configuration/secret/)
